#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const BOOTSTRAP_PAYLOAD_FILES = Object.freeze([
  "install.sh",
  "install.ps1",
  "scripts/bootstrap-entrypoint.sh",
  "scripts/bootstrap-entrypoint.ps1",
  "release-manifest.json",
  "docs/release/CHANGELOG.md",
]);

const BOOTSTRAP_GENERATED_FILES = Object.freeze(["release-assets.env"]);

function nextArgValue(argv, index, option) {
  const value = argv[index + 1];
  if (!value || String(value).startsWith("--")) {
    throw new Error(`missing_value:${option}`);
  }
  return String(value).trim();
}

function parseArgs(argv) {
  const args = {
    output: "",
    branch: "bootstrap",
    manifest: "",
  };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--output") {
      args.output = nextArgValue(argv, index, arg);
      index += 1;
    } else if (arg === "--branch") {
      args.branch = nextArgValue(argv, index, arg);
      index += 1;
    } else if (arg === "--manifest") {
      args.manifest = nextArgValue(argv, index, arg);
      index += 1;
    } else if (arg === "-h" || arg === "--help") {
      console.log(
        "Usage: npx tsx scripts/release/export-bootstrap-branch.ts --output <dir> [--branch bootstrap] [--manifest <path>]",
      );
      process.exit(0);
    } else {
      throw new Error(`unknown_argument:${arg}`);
    }
  }
  return args;
}

function rewriteBootstrapBranch(content, branch) {
  return content
    .replace(
      /^DEFAULT_BOOTSTRAP_BRANCH=.*$/m,
      `DEFAULT_BOOTSTRAP_BRANCH=${branch}`,
    )
    .replace(
      /^\$defaultBootstrapBranch = ".*"$/m,
      `$defaultBootstrapBranch = "${branch}"`,
    );
}

function shellQuote(value) {
  return `'${String(value ?? "").replace(/'/g, `'"'"'`)}'`;
}

function envKey(value) {
  return String(value || "")
    .trim()
    .replace(/[^A-Za-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toUpperCase();
}

function firstNonEmpty(...values) {
  for (const value of values) {
    const text = String(value || "").trim();
    if (text) return text;
  }
  return "";
}

function releaseSourceLabel(channel, entry) {
  const version = firstNonEmpty(entry?.version, "0.0.0");
  if (channel === "stable") return `stable ${version}`;
  if (channel === "beta") return `beta ${version}`;
  return `nightly ${version}`;
}

function writeReleaseAssetsEnv(manifestPath, outputDir) {
  let manifest = {};
  try {
    manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  } catch {}
  const lines = [
    "# Generated by scripts/release/export-bootstrap-branch.ts.",
    "# Shell bootstrap uses this optional file to install platform bundles without system node/npm.",
  ];
  for (const channel of ["stable", "beta", "nightly"]) {
    const entry = manifest[channel] || {};
    const assets = entry.assets || {};
    for (const [platform, asset] of Object.entries(assets)) {
      const prefix = `RIN_ASSET_${envKey(channel)}_${envKey(platform)}`;
      const bundleUrl = firstNonEmpty(asset.bundleUrl, asset.archiveUrl);
      if (!bundleUrl) continue;
      const fields = {
        URL: bundleUrl,
        SHA256: asset.sha256,
        NODE_VERSION: asset.nodeVersion,
        VERSION: entry.version,
        BRANCH:
          channel === "stable"
            ? "stable"
            : channel === "beta"
              ? "beta"
              : firstNonEmpty(entry.branch, "main"),
        REF: entry.ref,
        SOURCE_LABEL: releaseSourceLabel(channel, entry),
      };
      for (const [name, value] of Object.entries(fields)) {
        const text = String(value || "").trim();
        if (text) lines.push(`${prefix}_${name}=${shellQuote(text)}`);
      }
    }
  }
  fs.writeFileSync(
    path.join(outputDir, "release-assets.env"),
    `${lines.join("\n")}\n`,
    "utf8",
  );
}

function copyFile(repoRoot, relativePath, outputDir, args, manifestPath) {
  const source =
    relativePath === "release-manifest.json"
      ? manifestPath
      : path.join(repoRoot, relativePath);
  const target = path.join(outputDir, relativePath);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  if (relativePath === "install.sh" || relativePath === "install.ps1") {
    const content = fs.readFileSync(source, "utf8");
    fs.writeFileSync(
      target,
      rewriteBootstrapBranch(content, args.branch),
      "utf8",
    );
    return;
  }
  fs.copyFileSync(source, target);
}

const args = parseArgs(process.argv.slice(2));
if (!args.output) throw new Error("missing_output_dir");
const repoRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
);
const outputDir = path.resolve(process.cwd(), args.output);
const manifestPath = args.manifest
  ? path.resolve(process.cwd(), args.manifest)
  : path.join(repoRoot, "release-manifest.json");
fs.mkdirSync(outputDir, { recursive: true });
for (const entry of fs.readdirSync(outputDir)) {
  if (entry === ".git") continue;
  fs.rmSync(path.join(outputDir, entry), { recursive: true, force: true });
}

for (const relativePath of BOOTSTRAP_PAYLOAD_FILES) {
  copyFile(repoRoot, relativePath, outputDir, args, manifestPath);
}
writeReleaseAssetsEnv(manifestPath, outputDir);

fs.writeFileSync(
  path.join(outputDir, "README.md"),
  [
    "# Rin bootstrap branch",
    "",
    `This branch is generated for the ${args.branch} bootstrap flow.`,
    "It only stores the install/update bootstrap entry scripts and release metadata.",
    "Do not develop Rin source code on this branch.",
    "",
    "Included files:",
    ...BOOTSTRAP_PAYLOAD_FILES.map((relativePath) => `- ${relativePath}`),
    ...BOOTSTRAP_GENERATED_FILES.map((relativePath) => `- ${relativePath}`),
    "",
  ].join("\n"),
  "utf8",
);

console.log(`Exported bootstrap files to ${outputDir}`);
